services:
  frontend:
    build:
      context: ${FRONTEND_PATH:-./trs-frontend}
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ${FRONTEND_PATH:-./trs-frontend}:/app
      - /app/node_modules
  api:
    build:
      context: ${API_PATH:-./trs-api}
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ${API_PATH:-./trs-api}:/app
      - /app/node_modules